site_name: SwiftDiner Docs
site_url: https://swfitdiner.readthedocs.io/
repo_url: https://github.com/mojeedoyedeji/swiftdiner-docs
docs_dir: source
theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started:
      - Overview: source/getting-started/overview.md
      - System Requirements: source/getting-started/system-requirements.md
      - Signing Up & Logging In: source/getting-started/signup-login.md
      - Navigating the Dashboard: source/getting-started/dashboard.md
      - User Roles & Permissions: source/getting-started/user-roles.md
  - User Guide:
      - Food SMEs:
          - Setting Up a Business Profile: source/user-guide/food-sme/profile.md
          - Managing Menu Items: source/user-guide/food-sme/menu.md
          - Receiving & Managing Orders: source/user-guide/food-sme/orders.md
          - Payments & Payouts: source/user-guide/food-sme/payments.md
          - Customer Communication: source/user-guide/food-sme/communication.md
      - Customers:
          - Searching for Restaurants: source/user-guide/customers/search.md
          - Placing Orders: source/user-guide/customers/orders.md
          - Tracking Orders: source/user-guide/customers/tracking.md
          - Payment Methods & Refunds: source/user-guide/customers/payments.md
      - Delivery Services:
          - Registering as a Partner: source/user-guide/delivery/register.md
          - Accepting Delivery Requests: source/user-guide/delivery/requests.md
          - Delivery Tracking & Completion: source/user-guide/delivery/tracking.md
  - Admin Guide:
      - Managing Users: source/admin-guide/users.md
      - Platform Configuration: source/admin-guide/config.md
      - Order & Payment Management: source/admin-guide/orders-payments.md
      - Monitoring System Performance: source/admin-guide/performance.md
  - API Documentation:
      - Overview: source/api-docs/overview.md
      - Authentication & Authorization: source/api-docs/auth.md
      - Endpoints for SMEs: source/api-docs/sme-endpoints.md
      - Endpoints for Customers: source/api-docs/customer-endpoints.md
      - Endpoints for Delivery Services: source/api-docs/delivery-endpoints.md
      - Webhooks & Events: source/api-docs/webhooks.md
      - Rate Limits & Errors: source/api-docs/errors.md
  - Deployment & Configuration:
      - Installing SwiftDiner: source/deployment/install.md
      - Environment Variables: source/deployment/env-vars.md
      - Database Setup & Migrations: source/deployment/database.md
      - Hosting & Deployment: source/deployment/hosting.md
  - Security & Compliance:
      - Data Privacy & GDPR: source/security/privacy.md
      - Secure Payments: source/security/payments.md
      - Authentication & Access Control: source/security/auth.md
      - Fraud Prevention: source/security/fraud.md
  - Troubleshooting & FAQs:
      - Common Issues: source/troubleshooting/issues.md
      - Contacting Support: source/troubleshooting/support.md
      - Reporting Bugs: source/troubleshooting/bugs.md
  - Contribution Guide:
      - Writing Docs with MkDocs: source/contribute/mkdocs.md
      - Submitting Changes: source/contribute/contributing.md
      - Version Control & Releases: source/contribute/versioning.md
  - Glossary & References:
      - Key Terms: source/glossary/terms.md
      - External Resources: source/glossary/references.md
