site_name: SwiftDiner Docs
theme:
  name: readthedocs
  highlightjs: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
